- name: Install required packages
  become: true
  tags:
    - debian
    - rasberrypi
    - install-docker-required-packages
  when: ansible_os_family == "Debian"
  block:
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ boostrap_docker_packages }}"
        state: present
      tags: packages

- name: Add docker repository
  become: true
  tags:
    - debian
    - rasberrypi
    - add-docker-repository
  when: ansible_os_family == "Debian"
  block:
    - name: Add docker repository key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: present

    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
        filename: docker
        update_cache: true

- name: Install docker
  become: true
  tags:
    - debian
    - rasberrypi
    - install-docker
  when: ansible_os_family == "Debian"
  block:
    - name: Install docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
      tags: packages
