- name: Boostrap docker
  hosts: gitlab-runners
  tasks:
    - name: Include bootstrap docker
      ansible.builtin.include_role:
        name: bootstrap_docker
      tags: bootstrap-docker

- name: Install runner
  hosts: gitlab-runners
  become: true
  tags: Install
  tasks:
    - name: Start gitlab runner docker
      community.docker.docker_container:
        name: gitlab-runner
        image: gitlab/gitlab-runner:latest
        restart_policy: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /srv/gitlab-runner/config:/etc/gitlab-runner

- name: Register runner
  hosts: gitlab-runners
  tags: Register
  become: true
  tasks:
    - name: Register runner
      community.docker.docker_container_exec:
        container: gitlab-runner
        command: >
          gitlab-runner register --non-interactive
          --url https://gitlab.com/
          --registration-token {{ gitlab_runner_token }}
          --executor docker
          --docker-image alpine:latest
          --description {{ inventory_hostname }}
          --tag-list "docker,ansible"
          --run-untagged
          --locked=false
          --access-level=not_protected
      register: result
      when: gitlab_runner_token is defined
    - name: Show result
      tags: Register
      ansible.builtin.debug:
        var: result
      when: gitlab_runner_token is defined
