- name: Install nginx reverse proxy manager
  hosts: reverse-proxy
  become: true
  tasks:
    - name: Start docker nginx reverse proxy manager
      community.docker.docker_container:
        name: nginx-proxy-manager
        image: "jc21/nginx-proxy-manager:latest"
        restart_policy: unless-stopped
        ports:
          - "80:80"
          - "81:81"
          - "443:443"
        volumes:
          - "/srv/docker/nginx-proxy-manager/data:/data"
          - "/srv/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt"
          - "/srv/docker/nginx-proxy-manager/var/log:/var/log"
        healthcheck:
          test: ["CMD", "/usr/bin/check-health"]
          interval: 10s
          timeout: 3s
