- name: Update package on all host
  hosts: all
  become: true
  tags:
    - update-package
  tasks:
    - name: Update package
      ansible.builtin.include_role:
        name: upgrade_package

- name: Update dist
  hosts: all
  become: true
  tags:
    - update-dist
  tasks:
    - name: Update dist
      ansible.builtin.include_role:
        name: upgrade_dist
