- name: Update upgrade
  become: true
  tags:
    - debian
  when: ansible_os_family == "Debian"
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      tags: update
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: "*"
        state: latest
        autoremove: true
        autoclean: true
      tags: upgrade
